import { signInUser } from "./AuthActions/AuthActions";

import {
  postProduct,
  getProductData,
  getProductDataById,
  getProductDetailPosCart,
  deleteProductDataById,
  getProductNumber,
  updateProductById,
  getSuggestionProductName,
} from "./ProductAction/ProductAction";

import {
  getReferenceId,
  getOrderHistoryData,
  deleteHoldRecord,
  getOrderHistoryProducts,
  postPayment,
  getBankDetails,
  sendSMSReceiptLink,
  getSuggestionProductNameForPOS,
} from "./PosAction/PosAction";

import { getProfileData } from "./ProfileActions/ProfileActions";
import {
  wholeSalePayment,
  wholeSaleViewPayment,
  getWareHouseData,
  getWholeSaleTransactionData,
  deleteWholeSaleTransactionData,
  getWholeSaleRecordById,
  updateWholeSalePayment,
  getQuotationDataByQuotationNo,
  getSuggestionProductNameForWholesale,
} from "./SaleAction/SaleAction";

import {
  postGroupPermissionSettings,
  getBrand,
  deleteBrand,
  updateBrand,
  addBrand,
  getCategory,
  addCategory,
  deleteCategory,
  updateCategory,
  getCurrency,
  addCurrency,
  deleteCurrency,
  getUnits,
  addUnits,
  deleteUnits,
  updateUnit,
  addSystemSetting,
  updateSystemSetting,
  getSystemSetting,
  updatePosSetting,
  getPosSetting,
  addPosSetting,
  getBrandNoPagination,
  getByIdCategory,
  getByIdSubCategory,
  getDepartments,
  getByDeptCategory,
  getRoleById,
  updateGroupPermissionSettings,
  createDepartment,
  updateDepartment,
} from "./SettingAction/SettingAction";

import {
  getAllRoles,
  getMyPermissionsWithoutToken,
} from "./PermissionAction/PermissionAction";

import {
  getCustomerList,
  addUser,
  checkUser,
  editUser,
  getUsers,
  addCustomer,
  deleteCustomer,
  getRegistrationNumber,
  updateCustomer,
  getSupplier,
  addSupplier,
  updateSupplier,
  deleteSupplier,
  getCustomerRecord,
  getSuggestionCustomerName,
  getSuggestionForSupplier,
  getSuggestionUser,
  getAllUserRoleList,
  getSaleTransactionByUserId,
  getSaleReturnTransactionByUserId,
  getPurchaseReturnTransactionByUserId,
  addTill,
  getAllTill,
  deleteTill,
  getAllTillWithoutToken,
  editTill,
  updateUserTillStatus,
} from "./PeopleActions/PeopleActions";

import {
  getVegFruitList,
  postVegFruitList,
  deleteVegFruitList,
  updateVegFruitList,
  getByIdVegFruitList,
  getSuggestionVegFruitName,
} from "./VegetablesFruitsActions/VegetablesFruitsActions";

import {
  upDateStockByBarcodeId,
  updateProductNewStock,
  getStockHistory,
  addNewStock,
  getStockById,
  getProductDataByStockId,
  updateNewStock,
  deleteStock,
  getSupplierList,
  getSuggestionStockProductName,
} from "./StockAction/StockAction";

import {
  getSaleReturnDataBySearch,
  createSaleReturn,
  getSaleReturnTransaction,
  deleteSaleReturnTransactionData,
} from "./SaleReturn/SaleReturnAction";
import {
  quotationSubmit,
  getQuotationList,
  getQuotationRecordById,
  getSuggestionProductNameForQuotation,
  updateQuotation,
  sendMailToCustomer,
} from "./NewQuotationAction/NewQuotationAction";

import {
  createPurchase,
  getPurchaseListData,
  getPurchaseHistoryById,
  updatePurchase,
  getDataByInvoiceNumber,
  createPurchaseReturn,
  getPurchaseReturnHistory,
  paymentViewPayment,
  getSuggestionProductNameForPurchase,
  deleteTransactionRecord,
  minusMissedQtyPrice,
  getProductForSettleBill,
  createPurchaseProductSettleBill,
} from "./PurchaseAction/PurchaseAction";

import {
  createDiscount,
  getAllDiscountList,
  updateDiscount,
  getDiscountById,
  createProductDiscount,
  getAllDiscountProductList,
  updateProductDiscount,
  getProductDiscountById,
  deleteProductDiscount,
  deleteVegFruitDiscount,
  getSuggestionProductNameForDiscount,
} from "./DiscountAction/DiscountAction";

import {
  getTotalRetailSale,
  getTotalWholeSale,
  getTopFiveCustomer,
  getTotalPurchase,
  getTopFiveRetailProducts,
  getTopFiveWholeSaleProducts,
  getRecentRetailSale,
  getRecentWholeSale,
  getTotalRetailSaleReturn,
  getTotalWholeSaleReturn,
  getTotalPurchaseReturn,
  getTotalSale,
  getStockAlertList,
  getTopLeastSellingWholesaleProduct,
  getTopLeastSellingRetailProduct,
  getTotalExpenses,
  getUserPosTotal,
  getUserTillList,
  resetTill,
} from "./DashboardAction/DashboardAction";

import {
  getPurchaseReport,
  getPurchasePaymentReport,
  getPurchaseReturnReport,
  getProductReport,
  getStockReport,
  getSaleTransactionReport,
  getSalePaymentReport,
  getSaleReturnReport,
  getUserReportList,
  getSupplierReportList,
  getCustomerReportList,
  getTopLeastProducts,
  getTopSellingProducts,
  getZReportList,
  getStockEvaluationProductReport,
  getStockEvaluationVegFruitReport,
  getExpensesReport,
} from "./ReportAction/ReportAction";

import { getExpensesHistoryById } from "./ExpensesAction/ExpensesAction";

import { deleteMixMatchDiscount } from "./MixMatchAction/MixMatchAction";

export {
  getCustomerRecord,
  signInUser,
  postProduct,
  getProductData,
  getProductDataById,
  getOrderHistoryData,
  getReferenceId,
  getCustomerList,
  deleteHoldRecord,
  postGroupPermissionSettings,
  getProductDetailPosCart,
  getProfileData,
  getBrand,
  deleteBrand,
  updateBrand,
  addBrand,
  deleteProductDataById,
  getOrderHistoryProducts,
  postPayment,
  getAllRoles,
  addUser,
  checkUser,
  editUser,
  getUsers,
  getCategory,
  addCategory,
  deleteCategory,
  updateCategory,
  getCurrency,
  addCurrency,
  deleteCurrency,
  getUnits,
  addUnits,
  deleteUnits,
  updateUnit,
  addSystemSetting,
  updateSystemSetting,
  getSystemSetting,
  updatePosSetting,
  getPosSetting,
  addPosSetting,
  addCustomer,
  updateProductNewStock,
  getByIdVegFruitList,
  getVegFruitList,
  postVegFruitList,
  deleteVegFruitList,
  getSuggestionVegFruitName,
  updateVegFruitList,
  deleteCustomer,
  getRegistrationNumber,
  updateCustomer,
  getSupplier,
  addSupplier,
  updateSupplier,
  deleteSupplier,
  getSuggestionCustomerName,
  getSuggestionForSupplier,
  getSuggestionUser,
  getProductNumber,
  updateProductById,
  getSuggestionProductName,
  upDateStockByBarcodeId,
  getStockHistory,
  addNewStock,
  getStockById,
  getProductDataByStockId,
  updateNewStock,
  getBankDetails,
  getBrandNoPagination,
  getByIdCategory,
  getByIdSubCategory,
  deleteStock,
  getDepartments,
  getByDeptCategory,
  wholeSalePayment,
  wholeSaleViewPayment,
  getWareHouseData,
  getWholeSaleTransactionData,
  deleteWholeSaleTransactionData,
  getWholeSaleRecordById,
  updateWholeSalePayment,
  getSaleReturnDataBySearch,
  createSaleReturn,
  getSaleReturnTransaction,
  deleteSaleReturnTransactionData,
  quotationSubmit,
  getQuotationList,
  getQuotationRecordById,
  getSuggestionProductNameForQuotation,
  updateQuotation,
  getQuotationDataByQuotationNo,
  getSuggestionProductNameForWholesale,
  createPurchase,
  paymentViewPayment,
  getPurchaseListData,
  getPurchaseHistoryById,
  updatePurchase,
  getDataByInvoiceNumber,
  createPurchaseReturn,
  getPurchaseReturnHistory,
  getSuggestionProductNameForPurchase,
  sendMailToCustomer,
  createDiscount,
  getAllDiscountList,
  updateDiscount,
  getDiscountById,
  sendSMSReceiptLink,
  getSuggestionProductNameForPOS,
  getTotalRetailSale,
  getTotalWholeSale,
  getTopFiveCustomer,
  getTotalPurchase,
  getTopFiveRetailProducts,
  getTopFiveWholeSaleProducts,
  getRecentRetailSale,
  getRecentWholeSale,
  getTotalRetailSaleReturn,
  getTotalWholeSaleReturn,
  getTotalPurchaseReturn,
  createProductDiscount,
  getAllDiscountProductList,
  updateProductDiscount,
  getProductDiscountById,
  getSuggestionProductNameForDiscount,
  getPurchaseReport,
  getPurchasePaymentReport,
  getPurchaseReturnReport,
  getProductReport,
  getStockReport,
  getSaleTransactionReport,
  getSalePaymentReport,
  getSaleReturnReport,
  getUserReportList,
  getSupplierReportList,
  getCustomerReportList,
  getTotalSale,
  getStockAlertList,
  getTopLeastSellingWholesaleProduct,
  getTopLeastSellingRetailProduct,
  getTopLeastProducts,
  getTopSellingProducts,
  getSupplierList,
  getRoleById,
  updateGroupPermissionSettings,
  getZReportList,
  getExpensesHistoryById,
  createDepartment,
  updateDepartment,
  getTotalExpenses,
  getStockEvaluationProductReport,
  getStockEvaluationVegFruitReport,
  deleteProductDiscount,
  deleteVegFruitDiscount,
  deleteMixMatchDiscount,
  getAllUserRoleList,
  getSaleTransactionByUserId,
  getSaleReturnTransactionByUserId,
  getPurchaseReturnTransactionByUserId,
  deleteTransactionRecord,
  getExpensesReport,
  getUserPosTotal,
  addTill,
  getAllTill,
  deleteTill,
  getAllTillWithoutToken,
  editTill,
  getUserTillList,
  getMyPermissionsWithoutToken,
  resetTill,
  minusMissedQtyPrice,
  getProductForSettleBill,
  createPurchaseProductSettleBill,
  updateUserTillStatus,
  getSuggestionStockProductName,
};
