export const PRODUCT_VALUES = {
  productNumber: "",
  barCodeId: "",
  productName: "",
  SupplierName: "",
  category: "",
  brand: "",
  retailPrice: "",
  wholeSalePrice: "",
  actualCost: "",
  actualCostTotal: "",
  productCost: "",
  productUnit: "",
  retailPriceTotal: "",
  wholeSalePriceTotal: "",
  tax: 0,
  warehouse: "",
  country: "",
  // ProductUnitQuantity: "",
  // notes: "",
  imageUploads: [],
};
